// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdmvjnarmkirbahcgmen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kbXZqbmFybWtpcmJhaGNnbWVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyODI4OTQsImV4cCI6MjA3NDg1ODg5NH0.JE9ohbFGO36rG97JIEDxJsKGsHgkh36QWyIZk7HLL-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});